import { Roboto } from 'next/font/google';
import "./globals.css";
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata = {
  title: "ShoeHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${roboto.className} antialiased min-h-screen`}
      >
       <main className='min-h-screen'>
         {children}
       </main>
      </body>
    </html>
  );
}